import { Inter } from "next/font/google";
import Head from "next/head"; // Import Head component
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PG-AGI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Set title dynamically */}
        <title>{metadata.title}</title>
        {/* Add favicon */}
        <link rel="icon" href="/images/pgagi.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
