import { Inter } from "next/font/google";
import Head from "next/head"; // Import Head component
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PG-AGI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head> {/* Add Head component here */}
        <title>{metadata.title}</title> {/* Set title dynamically */}
        <link rel="/images/pgagi.png" href="/favicon.ico" /> {/* Add favicon */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
